modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="tarferss_minecraft_improvement"
version="1.0.0"
displayName="Tarfers's Minecraft improvement"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Tarfer 54, MCreator"

[[dependencies.tarferss_minecraft_improvement]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.tarferss_minecraft_improvement]]
    modId="crafttweaker"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tarferss_minecraft_improvement]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

